Correct JavaScript MIME types + extensions per RFC 9239
jshttp/mime-db pull request #262
Opened 2022-05-07 08:30 UTC by mathiasbynens

This patch updates the MIME type configuration per RFC 9239.
https://www.rfc-editor.org/rfc/rfc9239

First, the recommended MIME type is now `text/javascript`:

> The most widely supported media type in use is `text/javascript`; all
> others are considered historical and obsolete aliases of `text/javascript`.

Second, the `.mjs` extension is now explicitly registered:

> The `.mjs` file extension signals that the file represents a JavaScript
> module. Execution environments that rely on file extensions to
> determine how to process inputs parse `.mjs` files using the Module
> grammar of [ECMA-262].

(mime-db already included the `.mjs` extension prior to this patch, so no
change needed here.)

IANA template: https://www.iana.org/assignments/media-types/text/javascript

2022-05-07 08:31 UTC, mathiasbynens commented
Related PRs:

- [apache/httpd PR](https://github.com/apache/httpd/pull/318)
- [nginx/nginx PR](https://github.com/nginx/nginx/pull/77)

2022-05-07 11:44 UTC, dougwilson requested changes
Hello, and thank you for your pull request. Unfortunately this cannot be accepted as-is, as the `db.json` file is a generated file and changes made to it directly will just be overwritten when `npm run build` is run. Please see https://github.com/jshttp/mime-db#contributing for how to make contributions to the database.

2022-05-08 09:51 UTC, mathiasbynens commented
@dougwilson Thanks. It looks like it’s been a while since the scripts have been run, since there are a bunch of changes unrelated to this new RFC. I also noticed that some tweaks to the scripts are required in order to even pick up the new RFC.

Here’s what I think we should do, in order:

- [ ] Update IANA types by running scripts/fetch-iana: #264
- [ ] Allow scripts/fetch-iana to follow redirects: #263
- [ ] Remove the hardcoded and now unnecessary entries from `custom-types.json`: TODO

2022-05-12 08:58 UTC, mathiasbynens commented
Thanks @dougwilson! It looks like https://github.com/jshttp/mime-db/commit/c8e4e30da4571d55003f7d582ce4cd7080ab26b0 picks up the upstream `text/javascript` changes 🎉 What’s still missing is the `extensions` property set to `[".js", ".mjs"]` (even though both extensions are explicitly listed in the IANA registrations). I’ve updated this PR to fix that by adding it to `custom-types.json`.

2022-05-20 20:09 UTC, dougwilson approved these changes

2022-05-20 20:09 UTC, merged