Update iana-types.json
jshttp/mime-db pull request #295
Opened 2023-06-15 22:12 UTC by pzsette

Add 'dcm' extension to application/dicom mime. 'dcm' is the recommended extension for this multimedia type as stated at point 4 of additional information in this iana.org page https://www.iana.org/assignments/media-types/application/dicom.

2023-07-31 09:21 UTC, DimitriPapadopoulos commented
Looks like a dpulicate of #287.

2023-08-03 17:53 UTC, pzsette commented
@DimitriPapadopoulos How long does it take to approve the pull request?

2023-08-03 17:55 UTC, dougwilson requested changes
Hello, and thank you for your contribution. Unfortunately the file you changed is a generated file and your changes would be overridden. Please see our contribution instructions at https://github.com/jshttp/mime-db#direct-inclusion

2023-08-03 17:56 UTC, dougwilson commented
Sorry, I thought I already commented on it, but apparently I never submitted the comment. The PR needs to be updated to change a non generated file.

2023-08-03 18:29 UTC, DimitriPapadopoulos commented
@dougwilson So #287 **is** the correct fix after all, with `"application/dicom"` split between `src/iana-types.json` for the part extracted as is from the IANA database, and the addition in `src/custom-types.json`?

Shouldn't the IANA database be fixed upstream?

2025-03-05 15:51 UTC, wesleytodd commented
Yes, I believe that if you resolve the issues in #287 that would be the correct update. That is unless since 2023 the upstream had been fixed to include the extension. I will leave it to you to decide what the next steps are for that one, but will close this one in the mean time.

2025-03-05 15:51 UTC, closed without merging