Add Procreate Brush and Brush Set MIME Types
jshttp/mime-db pull request #339
Opened 2024-11-11 18:48 UTC by jeffreybaird

#### Description
This PR introduces new MIME types for Procreate-specific file formats:
- **`application/vnd.procreate.brush`** for `.brush` files
- **`application/vnd.procreate.brushset`** for `.brushset` files

These MIME types correspond to Procreate’s custom brush and brush set formats, commonly used shared by artists and designers on the Procreate app.

#### Details
- **application/vnd.procreate.brush**  
  - **Extensions**: `.brush`
  - **Description**: Procreate Brush
  - **Sources**: [Procreate Handbook - Brush Sharing](https://help.procreate.com/procreate/handbook/brushes/brushes-share)
  
- **application/vnd.procreate.brushset**  
  - **Extensions**: `.brushset`
  - **Description**: Procreate Brush Set
  - **Sources**: [Procreate Handbook - Brush Sharing](https://help.procreate.com/procreate/handbook/brushes/brushes-share)

#### References
The MIME types are based on Procreate’s file sharing guidelines and community conventions.

2024-11-14 16:34 UTC, wesleytodd requested changes

2024-11-14 16:34 UTC, wesleytodd commented on db.json
> +  },
Changes here are automated. The below changes are all that should be necessary.

2025-03-06 21:23 UTC, bjohansebas approved these changes

2025-03-07 15:03 UTC, wesleytodd approved these changes

2025-03-07 15:04 UTC, merged