Add Adobe DNG file
jshttp/mime-db pull request #340
Opened 2024-11-11 19:03 UTC by jeffreybaird

#### Description
This PR introduces a new MIME type for Adobe Digital Negative (DNG) files:
- **`image/x-adobe-dng`** for `.dng` files

The DNG format is a non-proprietary file format developed by Adobe for storing raw image data from digital cameras. It provides photographers and developers with a standardized format for raw images.

#### Details
- **image/x-adobe-dng**  
  - **Extensions**: `.dng`
  - **Description**: A non-proprietary file format for storing camera raw files
  - **Sources**: [Adobe DNG Specification (PDF)](https://paulbourke.net/dataformats/dng/dng_spec_1_6_0_0.pdf)

#### References
The MIME type is based on the official Adobe DNG specification, which details the structure and purpose of the file format.

2024-11-14 16:35 UTC, wesleytodd requested changes

2024-11-14 16:35 UTC, wesleytodd commented on db.json
> +  },
Same as the others. The custom types should be the only addition.

2025-03-06 20:27 UTC, bjohansebas approved these changes

2025-03-07 15:09 UTC, wesleytodd approved these changes

2025-03-07 15:09 UTC, merged