Add support for Procreate Dreams
jshttp/mime-db pull request #341
Opened 2024-11-11 19:19 UTC by jeffreybaird

**Description:** Introduces the MIME type `application/vnd.procreate.dream`, which corresponds to Procreate Dreams project files (`.drm` extension).

**Details:**

- **MIME Type**: `application/vnd.procreate.dream`
- **Extensions**: `.drm`
- **Description**: A proprietary file type used by Procreate Dreams for saving animation project data.
- **Sources**:
  - [Exporting Movies - Procreate Help](https://help.procreate.com/articles/dxjyml-exporting-movies)
  - [Export Formats - Procreate Help](https://help.procreate.com/articles/deaqnd-export-formats#d43a8f399706)

2024-11-11 19:25 UTC, bjohansebas approved these changes

2024-11-14 16:35 UTC, wesleytodd approved these changes

2024-11-14 16:35 UTC, wesleytodd commented on db.json
> +  },
Same, remove this change and just submit the other file.

2024-11-14 16:36 UTC, wesleytodd requested changes
oops clicked wrong option.

2025-03-06 21:27 UTC, bjohansebas approved these changes

2025-03-07 15:02 UTC, wesleytodd approved these changes

2025-03-07 15:03 UTC, merged