replace got with undici
jshttp/mime-db pull request #352
Opened 2024-12-13 17:31 UTC by bjohansebas

Unlike what #347 does, got is replaced with undici, avoiding the use of try-catch, with the same result. It might improve the workflow speed, but that's the least important thing (in my opinion).

2024-12-20 14:41 UTC, UlisesGascon approved these changes
LGTM! I like the idea of using undici in this scenario :+1:

2024-12-20 14:41 UTC, UlisesGascon commented on scripts/fetch-iana.js
> +  const mimes = await toArray(parser(await res.body.text()))
```suggestion
  const responseText = await res.body.text();
  const mimes = await toArray(parser(responseText));
```

I believe this approach improves readability and makes the code easier to maintain.

2025-01-06 15:15 UTC, bjohansebas commented on scripts/fetch-iana.js
> +  const mimes = await toArray(parser(await res.body.text()))
Done

2025-01-07 07:55 UTC, UlisesGascon commented
Not sure why the coverage is failing, but does not seems related (IMO) https://github.com/jshttp/mime-db/actions/runs/12635017301/job/35239389864?pr=352

2025-01-07 15:45 UTC, bjohansebas commented on scripts/fetch-iana.js
> -  addSource(data, res.url)
Undici does not provide the `url` property, so I had to create a variable and update it manually to replicate the behavior.

2025-01-07 16:04 UTC, bjohansebas commented on scripts/fetch-iana.js
> -  addSource(data, res.url)
We're also no longer receiving redirects since I changed the URL that was causing the redirect in:

https://github.com/jshttp/mime-db/blob/e7548fb503f2f1015026c09012b47e2abe7a82a6/scripts/fetch-iana.js#L113-115

2025-01-08 16:11 UTC, wesleytodd requested changes

2025-01-08 16:11 UTC, wesleytodd commented on scripts/utils.js
> +const { request } = require('undici')
I am not sure I understand the need for this file? Do we need this user agent at all? If so, we should comment about it because it seems like this entire file exists just to set that, otherwise we could just import `unidici` directly into each of the scripts.

EDIT: I should add I consider any file/directory with `util` as the name a "smell". Meaning it was not well thought out. In this case, the file should be called `request` if you really do need it.

2025-01-08 16:17 UTC, bjohansebas commented on scripts/utils.js
> +const { request } = require('undici')
This file is necessary because, for some reason, the user-agent header is not being sent, and it is only for configuration. It is required to make requests to IANA, otherwise, the request would fail without that header.

2025-01-08 16:32 UTC, wesleytodd commented on scripts/utils.js
> +const { request } = require('undici')
Ok, can you document that reason in a comment in this file? With that change I will move it to an approval.

2025-01-08 16:39 UTC, bjohansebas commented on scripts/utils.js
> +const { request } = require('undici')
done

2025-01-08 17:50 UTC, wesleytodd approved these changes

2025-01-08 17:51 UTC, wesleytodd commented on scripts/fetch-iana.js
> -  addSource(data, res.url)
@jonchurch do you consider this resolved? If so I would like to merge this.

2025-03-05 15:36 UTC, wesleytodd commented on scripts/fetch-iana.js
> -  addSource(data, res.url)
@jonchurch friendly ping on this.

2025-03-05 16:16 UTC, jonchurch approved these changes

2025-03-05 16:19 UTC, merged